// flow-typed signature: f5dd69bddcae73d06e959553b4fd8bb5
// flow-typed version: <<STUB>>/react-redux-multilingual_v^1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-multilingual'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-multilingual' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-multilingual/example/App' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/example/index' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/example/server' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/example/translations' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/actions' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/provider' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/utils' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/lib/withTranslate' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/actions' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/index' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/provider' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/utils' {
  declare module.exports: any;
}

declare module 'react-redux-multilingual/src/withTranslate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-multilingual/example/App.js' {
  declare module.exports: $Exports<'react-redux-multilingual/example/App'>;
}
declare module 'react-redux-multilingual/example/index.js' {
  declare module.exports: $Exports<'react-redux-multilingual/example/index'>;
}
declare module 'react-redux-multilingual/example/server.js' {
  declare module.exports: $Exports<'react-redux-multilingual/example/server'>;
}
declare module 'react-redux-multilingual/example/translations.js' {
  declare module.exports: $Exports<'react-redux-multilingual/example/translations'>;
}
declare module 'react-redux-multilingual/example/webpack.config.js' {
  declare module.exports: $Exports<'react-redux-multilingual/example/webpack.config'>;
}
declare module 'react-redux-multilingual/lib/actions.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/actions'>;
}
declare module 'react-redux-multilingual/lib/index.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/index'>;
}
declare module 'react-redux-multilingual/lib/provider.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/provider'>;
}
declare module 'react-redux-multilingual/lib/reducer.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/reducer'>;
}
declare module 'react-redux-multilingual/lib/utils.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/utils'>;
}
declare module 'react-redux-multilingual/lib/withTranslate.js' {
  declare module.exports: $Exports<'react-redux-multilingual/lib/withTranslate'>;
}
declare module 'react-redux-multilingual/src/actions.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/actions'>;
}
declare module 'react-redux-multilingual/src/index.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/index'>;
}
declare module 'react-redux-multilingual/src/provider.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/provider'>;
}
declare module 'react-redux-multilingual/src/reducer.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/reducer'>;
}
declare module 'react-redux-multilingual/src/utils.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/utils'>;
}
declare module 'react-redux-multilingual/src/withTranslate.js' {
  declare module.exports: $Exports<'react-redux-multilingual/src/withTranslate'>;
}
